server:
  port: 8082


spring:
  application:
    name: dubbo-demo-consumer
  dubbo:
    application:
      name: ${spring.application.name}
#    protocol:
#      name: feign
#      port: ${server.port}
    registry:
      protocol: hazelcast
#      address: 224.5.6.7:1234?managementCenter=http://localhost:8080/mancenter
      address: 224.5.6.7:1234
    scan: com.example.service

logging:
  level:
    root: info
  file: ${spring.application.name}.log
management:
  security:
    enabled: false
